name: Manual Test - Weekly Update with Email

on:
  workflow_dispatch:

jobs:
  update-reading:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (if any)
      run: pip install -r requirements.txt || true

    - name: Run the update script
      run: python update_reading.py

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add index.html
        git commit -m "Manual test: update weekly content"
        git push

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "✅ Weekly Breathe site updated"
        to: ${{ secrets.NOTIFY_EMAIL }}
        from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
        body: |
          The weekly Breathe site content has been updated successfully.
          ✅ New reading, prayer, and exercise are live.
          Visit the site: https://yourusername.github.io/your-repo/
