name: Weekly Reading Update

on:
  schedule:
    - cron: '0 0 * * MON'  # Every Monday at 00:00 UTC
  workflow_dispatch:       # Allows manual trigger from GitHub Actions tab

jobs:
  update-reading:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (if any)
      run: pip install -r requirements.txt || true

    - name: Run the update script
      run: python update_reading.py

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add index.html
        git commit -m "Weekly content update [auto]"
        git push
